AES-NI: aes_key_expansion.c File Reference
aes_key_expansion.c File Reference
#include "aes/core/aes_key_expansion.h"
Functions
static void aes128_key_assist (__m128i *temp1, __m128i *temp2)
Helper function for AES-128 key expansion.
void aes128_key_expansion (const __m128i user_key, __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS])
Expands a 128-bit AES user key into the encryption round key schedule.
static void aes192_key_assist (__m128i *temp1, __m128i *temp2, __m128i *temp3)
Helper function for AES-192 key expansion.
void aes192_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS])
Expands a 192-bit AES user key into the encryption round key schedule.
static void aes256_key_assist (__m128i *temp1, __m128i *temp2, __m128i *temp3)
Helper function for AES-256 key expansion using AES-NI.
void aes256_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS])
Expands a 256-bit AES user key into the encryption round key schedule.
void aes128_invert_round_keys (const __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_128_NUM_ROUND_KEYS])
Inverts the AES-128 encryption round keys into decryption round keys.
void aes192_invert_round_keys (const __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_192_NUM_ROUND_KEYS])
Inverts the AES-192 encryption round keys into decryption round keys.
void aes256_invert_round_keys (const __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_256_NUM_ROUND_KEYS])
Inverts the AES-256 encryption round keys into decryption round keys.
Function Documentation
aes128_invert_round_keys()
void aes128_invert_round_keys (const __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_128_NUM_ROUND_KEYS])
Inverts the AES-128 encryption round keys into decryption round keys.
Parameters
enc_round_keys Input array of 11 encryption round keys from aes128_key_expansion().
dec_round_keys Output array of 11 decryption round keys.
Definition at line 239 of file aes_key_expansion.c.
{
    // First decryption round key = last encryption round key
    dec_round_keys[0]  = enc_round_keys[10];
    // Apply aesimc to intermediate keys (in reverse order)
    dec_round_keys[1]  = _mm_aesimc_si128(enc_round_keys[9]);
    dec_round_keys[2]  = _mm_aesimc_si128(enc_round_keys[8]);
    dec_round_keys[3]  = _mm_aesimc_si128(enc_round_keys[7]);
    dec_round_keys[4]  = _mm_aesimc_si128(enc_round_keys[6]);
    dec_round_keys[5]  = _mm_aesimc_si128(enc_round_keys[5]);
    dec_round_keys[6]  = _mm_aesimc_si128(enc_round_keys[4]);
    dec_round_keys[7]  = _mm_aesimc_si128(enc_round_keys[3]);
    dec_round_keys[8]  = _mm_aesimc_si128(enc_round_keys[2]);
    dec_round_keys[9]  = _mm_aesimc_si128(enc_round_keys[1]);
    // Last decryption round key = first encryption round key
    dec_round_keys[10] = enc_round_keys[0];
}
References AES_128_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes128_key_assist()
static void aes128_key_assist (__m128i * temp1, __m128i * temp2) inline static
Helper function for AES-128 key expansion.
Applies a sequence of left shifts and XORs to derive the next round key block, using the result of the AES key generation assist intrinsic.
Parameters
temp1 [in/out] Working key block being expanded.
temp2 [in] Output of _mm_aeskeygenassist_si128 used in round key derivation.
Definition at line 12 of file aes_key_expansion.c.
{
    __m128i temp4;
    // Perform 3 consecutive left shifts and XOR to diffuse the key material
    temp4 = _mm_slli_si128(*temp1, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    temp4 = _mm_slli_si128(temp4, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    temp4 = _mm_slli_si128(temp4, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    // Mix with the round constant from aeskeygenassist
    *temp1 = _mm_xor_si128(*temp1, _mm_shuffle_epi32(*temp2, 0xff));
}
Referenced by aes128_key_expansion().
aes128_key_expansion()
void aes128_key_expansion (const __m128i user_key, __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS])
Expands a 128-bit AES user key into the encryption round key schedule.
Parameters
user_key The 128-bit user key (single __m128i block).
enc_round_keys Output array of 11 __m128i encryption round keys (AES_128_WORDS).
Definition at line 28 of file aes_key_expansion.c.
{
    __m128i temp1 = user_key;
    __m128i temp2;
    enc_round_keys[0] = temp1; // Store the original user key as round key 0
    // Generate remaining 10 round keys
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x01);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[1] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x02);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[2] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x04);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[3] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x08);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[4] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x10);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[5] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x20);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[6] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x40);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[7] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x80);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[8] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x1B);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[9] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x36);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[10] = temp1;
}
References aes128_key_assist(), and AES_128_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes192_invert_round_keys()
void aes192_invert_round_keys (const __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_192_NUM_ROUND_KEYS])
Inverts the AES-192 encryption round keys into decryption round keys.
Parameters
enc_round_keys Input array of 13 encryption round keys from aes192_key_expansion().
dec_round_keys Output array of 13 decryption round keys.
Definition at line 259 of file aes_key_expansion.c.
{
    // First decryption round key = last encryption round key
    dec_round_keys[0]  = enc_round_keys[12];
    // Apply aesimc to intermediate keys (in reverse order)
    dec_round_keys[1]  = _mm_aesimc_si128(enc_round_keys[11]);
    dec_round_keys[2]  = _mm_aesimc_si128(enc_round_keys[10]);
    dec_round_keys[3]  = _mm_aesimc_si128(enc_round_keys[9]);
    dec_round_keys[4]  = _mm_aesimc_si128(enc_round_keys[8]);
    dec_round_keys[5]  = _mm_aesimc_si128(enc_round_keys[7]);
    dec_round_keys[6]  = _mm_aesimc_si128(enc_round_keys[6]);
    dec_round_keys[7]  = _mm_aesimc_si128(enc_round_keys[5]);
    dec_round_keys[8]  = _mm_aesimc_si128(enc_round_keys[4]);
    dec_round_keys[9]  = _mm_aesimc_si128(enc_round_keys[3]);
    dec_round_keys[10] = _mm_aesimc_si128(enc_round_keys[2]);
    dec_round_keys[11] = _mm_aesimc_si128(enc_round_keys[1]);
    // Last decryption round key = first encryption round key
    dec_round_keys[12] = enc_round_keys[0];
}
References AES_192_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes192_key_assist()
static void aes192_key_assist (__m128i * temp1, __m128i * temp2, __m128i * temp3) inline static
Helper function for AES-192 key expansion.
Performs key schedule mixing using left shifts, XORs, and shuffles. AES-192 requires managing two interleaved key parts and generates partial round keys every 64 or 128 bits.
Parameters
temp1 [in/out] First key part being expanded.
temp2 [in/out] Temporary result from _mm_aeskeygenassist_si128.
temp3 [in/out] Second key part being expanded.
Definition at line 88 of file aes_key_expansion.c.
{
    __m128i temp4;
    // Update temp1 (first part of the key)
    *temp2 = _mm_shuffle_epi32(*temp2, 0x55); // Extract specific word from keygen assist
    temp4 = _mm_slli_si128(*temp1, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    temp4 = _mm_slli_si128(temp4, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    temp4 = _mm_slli_si128(temp4, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    *temp1 = _mm_xor_si128(*temp1, *temp2);
    // Update temp3 (second part of the key)
    *temp2 = _mm_shuffle_epi32(*temp1, 0xff); // Prepare shuffle for temp3 update
    temp4 = _mm_slli_si128(*temp3, 0x4);
    *temp3 = _mm_xor_si128(*temp3, temp4);
    *temp3 = _mm_xor_si128(*temp3, *temp2);
}
Referenced by aes192_key_expansion().
aes192_key_expansion()
void aes192_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS])
Expands a 192-bit AES user key into the encryption round key schedule.
Parameters
user_key The 192-bit user key (as two __m128i blocks, only 192 bits used).
enc_round_keys Output array of 13 __m128i encryption round keys (AES_192_WORDS).
Definition at line 109 of file aes_key_expansion.c.
{
    __m128i temp1 = user_key[0];
    __m128i temp3 = user_key[1];
    __m128i temp2;
    enc_round_keys[0] = temp1; // Store the original user key as round key 0
    enc_round_keys[1] = temp3; // Store the second part of the user key as round key 1
    // Generate remaining 11 round keys
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x1);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[1] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[1]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[2] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x2);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[3] = temp1;
    enc_round_keys[4] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x4);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[4] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[4]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[5] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x8);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[6] = temp1;
    enc_round_keys[7] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x10);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[7] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[7]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[8] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x20);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[9] = temp1;
    enc_round_keys[10] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x40);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[10] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[10]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[11] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x80);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[12] = temp1;
}
References aes192_key_assist(), and AES_192_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes256_invert_round_keys()
void aes256_invert_round_keys (const __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_256_NUM_ROUND_KEYS])
Inverts the AES-256 encryption round keys into decryption round keys.
Parameters
enc_round_keys Input array of 15 encryption round keys from aes256_key_expansion().
dec_round_keys Output array of 15 decryption round keys.
Definition at line 281 of file aes_key_expansion.c.
{
    // First decryption round key = last encryption round key
    dec_round_keys[0]  = enc_round_keys[14];
    // Apply aesimc to intermediate keys (in reverse order)
    dec_round_keys[1]  = _mm_aesimc_si128(enc_round_keys[13]);
    dec_round_keys[2]  = _mm_aesimc_si128(enc_round_keys[12]);
    dec_round_keys[3]  = _mm_aesimc_si128(enc_round_keys[11]);
    dec_round_keys[4]  = _mm_aesimc_si128(enc_round_keys[10]);
    dec_round_keys[5]  = _mm_aesimc_si128(enc_round_keys[9]);
    dec_round_keys[6]  = _mm_aesimc_si128(enc_round_keys[8]);
    dec_round_keys[7]  = _mm_aesimc_si128(enc_round_keys[7]);
    dec_round_keys[8]  = _mm_aesimc_si128(enc_round_keys[6]);
    dec_round_keys[9]  = _mm_aesimc_si128(enc_round_keys[5]);
    dec_round_keys[10] = _mm_aesimc_si128(enc_round_keys[4]);
    dec_round_keys[11] = _mm_aesimc_si128(enc_round_keys[3]);
    dec_round_keys[12] = _mm_aesimc_si128(enc_round_keys[2]);
    dec_round_keys[13] = _mm_aesimc_si128(enc_round_keys[1]);
    // Last decryption round key = first encryption round key
    dec_round_keys[14] = enc_round_keys[0];
}
References AES_256_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes256_key_assist()
static void aes256_key_assist (__m128i * temp1, __m128i * temp2, __m128i * temp3) inline static
Helper function for AES-256 key expansion using AES-NI.
This function expands two 128-bit key parts (total 256-bit key) into new round key material. The expansion uses the result of _mm_aeskeygenassist_si128, shuffling, and repeated left shifts with XOR to generate strong diffusion.
Parameters
temp1 [in/out] First half of the key being expanded.
temp2 [in/out] Output from _mm_aeskeygenassist_si128 using current RCON value.
temp3 [in/out] Second half of the key being expanded.
Definition at line 170 of file aes_key_expansion.c.
{
    __m128i temp4;
    // Expand temp1 (first half of the key)
    *temp2 = _mm_shuffle_epi32(*temp2, 0xFF); // Broadcast one word from keygen assist
    temp4 = _mm_slli_si128(*temp1, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    temp4 = _mm_slli_si128(temp4, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    temp4 = _mm_slli_si128(temp4, 0x4);
    *temp1 = _mm_xor_si128(*temp1, temp4);
    *temp1 = _mm_xor_si128(*temp1, *temp2); // Mix with assist result
    // Expand temp3 (second half of the key)
    temp4 = _mm_aeskeygenassist_si128(*temp1, 0x00); // Generate assist from updated temp1
    temp4 = _mm_shuffle_epi32(temp4, 0xAA); // Broadcast relevant word
    *temp3 = _mm_xor_si128(*temp3, _mm_slli_si128(*temp3, 0x4));
    *temp3 = _mm_xor_si128(*temp3, _mm_slli_si128(*temp3, 0x4));
    *temp3 = _mm_xor_si128(*temp3, _mm_slli_si128(*temp3, 0x4));
    *temp3 = _mm_xor_si128(*temp3, temp4); // Final mixing with assist
}
Referenced by aes256_key_expansion().
aes256_key_expansion()
void aes256_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS])
Expands a 256-bit AES user key into the encryption round key schedule.
Parameters
user_key The 256-bit user key (two full __m128i blocks).
enc_round_keys Output array of 15 __m128i encryption round keys (AES_256_WORDS).
Definition at line 194 of file aes_key_expansion.c.
{
    __m128i temp1 = user_key[0]; // First half of the user key
    __m128i temp3 = user_key[1]; // Second half of the user key
    __m128i temp2;
    enc_round_keys[0] = temp1;
    enc_round_keys[1] = temp3;
    // Generate remaining 13 round keys
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x01);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[2] = temp1;
    enc_round_keys[3] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x02);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[4] = temp1;
    enc_round_keys[5] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x04);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[6] = temp1;
    enc_round_keys[7] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x08);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[8] = temp1;
    enc_round_keys[9] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x10);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[10] = temp1;
    enc_round_keys[11] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x20);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[12] = temp1;
    enc_round_keys[13] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x40);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[14] = temp1;
}
References aes256_key_assist(), and AES_256_NUM_ROUND_KEYS.
Referenced by aes_context_init().