AES-NI: aes_decrypt.h File Reference
aes_decrypt.h File Reference
AES block decryption functions (AES-128, AES-192, AES-256) using AES-NI.
#include "aes/core/aes_constants.h"
#include <emmintrin.h>
#include <wmmintrin.h>
Functions
void aes128_decrypt_block (const __m128i ciphertext, __m128i *plaintext, const __m128i dec_round_keys[AES_128_NUM_ROUND_KEYS])
Decrypts a single 128-bit block using AES-128.
void aes192_decrypt_block (const __m128i ciphertext, __m128i *plaintext, const __m128i dec_round_keys[AES_192_NUM_ROUND_KEYS])
Decrypts a single 128-bit block using AES-192.
void aes256_decrypt_block (const __m128i ciphertext, __m128i *plaintext, const __m128i dec_round_keys[AES_256_NUM_ROUND_KEYS])
Decrypts a single 128-bit block using AES-256.
Detailed Description
AES block decryption functions (AES-128, AES-192, AES-256) using AES-NI.
This header declares functions for decrypting a single 16-byte block using AES with hardware acceleration via Intel AES-NI intrinsics.
Each function requires precomputed decryption round keys, which can be derived from the encryption round keys using the corresponding inversion functions.
Definition in file aes_decrypt.h.
Function Documentation
aes128_decrypt_block()
void aes128_decrypt_block (const __m128i ciphertext, __m128i * plaintext, const __m128i dec_round_keys[AES_128_NUM_ROUND_KEYS])
Decrypts a single 128-bit block using AES-128.
Parameters
ciphertext Input 16-byte block to decrypt.
plaintext Output pointer to receive the decrypted 16-byte block.
dec_round_keys Array of 11 decryption round keys.
Definition at line 3 of file aes_decrypt.c.
{
    // Initial AddRoundKey
    __m128i tmp = _mm_xor_si128(ciphertext, dec_round_keys[0]);
    // 9 standard AES decryption rounds
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[1]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[2]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[3]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[4]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[5]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[6]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[7]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[8]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[9]);
    // Final round (AddRoundKey + SubBytes + ShiftRows)
    tmp = _mm_aesdeclast_si128(tmp, dec_round_keys[10]);
    // Store the result
    *plaintext = tmp;
}
References AES_128_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes192_decrypt_block()
void aes192_decrypt_block (const __m128i ciphertext, __m128i * plaintext, const __m128i dec_round_keys[AES_192_NUM_ROUND_KEYS])
Decrypts a single 128-bit block using AES-192.
Parameters
ciphertext Input 16-byte block to decrypt.
plaintext Output pointer to receive the decrypted 16-byte block.
dec_round_keys Array of 13 decryption round keys.
Definition at line 26 of file aes_decrypt.c.
{
    // Initial AddRoundKey
    __m128i tmp = _mm_xor_si128(ciphertext, dec_round_keys[0]);
    // 11 standard AES decryption rounds
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[1]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[2]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[3]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[4]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[5]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[6]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[7]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[8]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[9]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[10]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[11]);
    // Final round (AddRoundKey + SubBytes + ShiftRows)
    tmp = _mm_aesdeclast_si128(tmp, dec_round_keys[12]);
    // Store the result
    *plaintext = tmp;
}
References AES_192_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes256_decrypt_block()
void aes256_decrypt_block (const __m128i ciphertext, __m128i * plaintext, const __m128i dec_round_keys[AES_256_NUM_ROUND_KEYS])
Decrypts a single 128-bit block using AES-256.
Parameters
ciphertext Input 16-byte block to decrypt.
plaintext Output pointer to receive the decrypted 16-byte block.
dec_round_keys Array of 15 decryption round keys.
Definition at line 51 of file aes_decrypt.c.
{
    // Initial AddRoundKey
    __m128i tmp = _mm_xor_si128(ciphertext, dec_round_keys[0]);
    // 13 standard AES decryption rounds
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[1]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[2]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[3]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[4]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[5]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[6]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[7]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[8]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[9]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[10]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[11]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[12]);
    tmp = _mm_aesdec_si128(tmp, dec_round_keys[13]);
    // Final round (AddRoundKey + SubBytes + ShiftRows)
    tmp = _mm_aesdeclast_si128(tmp, dec_round_keys[14]);
    // Store the result
    *plaintext = tmp;
}
References AES_256_NUM_ROUND_KEYS.
Referenced by aes_context_init().