AES-NI: aes_key_expansion.h File Reference
aes_key_expansion.h File Reference
AES key expansion and inversion routines (AES-128, AES-192, AES-256).
#include "aes/core/aes_constants.h"
#include <emmintrin.h>
#include <wmmintrin.h>
Functions
void aes128_key_expansion (const __m128i user_key, __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS])
Expands a 128-bit AES user key into the encryption round key schedule.
void aes192_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS])
Expands a 192-bit AES user key into the encryption round key schedule.
void aes256_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS])
Expands a 256-bit AES user key into the encryption round key schedule.
void aes128_invert_round_keys (const __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_128_NUM_ROUND_KEYS])
Inverts the AES-128 encryption round keys into decryption round keys.
void aes192_invert_round_keys (const __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_192_NUM_ROUND_KEYS])
Inverts the AES-192 encryption round keys into decryption round keys.
void aes256_invert_round_keys (const __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_256_NUM_ROUND_KEYS])
Inverts the AES-256 encryption round keys into decryption round keys.
Detailed Description
AES key expansion and inversion routines (AES-128, AES-192, AES-256).
This header defines functions to generate encryption and decryption round keys for the AES algorithm, using Intel AES-NI intrinsics for efficient performance. These round keys are used during the AES block encryption and decryption process.
Functions are provided for each AES variant:
AES-128: 10 rounds, 11 round keys
AES-192: 12 rounds, 13 round keys
AES-256: 14 rounds, 15 round keys
Definition in file aes_key_expansion.h.
Function Documentation
aes128_invert_round_keys()
void aes128_invert_round_keys (const __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_128_NUM_ROUND_KEYS])
Inverts the AES-128 encryption round keys into decryption round keys.
Parameters
enc_round_keys Input array of 11 encryption round keys from aes128_key_expansion().
dec_round_keys Output array of 11 decryption round keys.
Definition at line 239 of file aes_key_expansion.c.
{
    // First decryption round key = last encryption round key
    dec_round_keys[0]  = enc_round_keys[10];
    // Apply aesimc to intermediate keys (in reverse order)
    dec_round_keys[1]  = _mm_aesimc_si128(enc_round_keys[9]);
    dec_round_keys[2]  = _mm_aesimc_si128(enc_round_keys[8]);
    dec_round_keys[3]  = _mm_aesimc_si128(enc_round_keys[7]);
    dec_round_keys[4]  = _mm_aesimc_si128(enc_round_keys[6]);
    dec_round_keys[5]  = _mm_aesimc_si128(enc_round_keys[5]);
    dec_round_keys[6]  = _mm_aesimc_si128(enc_round_keys[4]);
    dec_round_keys[7]  = _mm_aesimc_si128(enc_round_keys[3]);
    dec_round_keys[8]  = _mm_aesimc_si128(enc_round_keys[2]);
    dec_round_keys[9]  = _mm_aesimc_si128(enc_round_keys[1]);
    // Last decryption round key = first encryption round key
    dec_round_keys[10] = enc_round_keys[0];
}
References AES_128_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes128_key_expansion()
void aes128_key_expansion (const __m128i user_key, __m128i enc_round_keys[AES_128_NUM_ROUND_KEYS])
Expands a 128-bit AES user key into the encryption round key schedule.
Parameters
user_key The 128-bit user key (single __m128i block).
enc_round_keys Output array of 11 __m128i encryption round keys (AES_128_WORDS).
Definition at line 28 of file aes_key_expansion.c.
{
    __m128i temp1 = user_key;
    __m128i temp2;
    enc_round_keys[0] = temp1; // Store the original user key as round key 0
    // Generate remaining 10 round keys
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x01);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[1] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x02);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[2] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x04);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[3] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x08);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[4] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x10);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[5] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x20);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[6] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x40);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[7] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x80);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[8] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x1B);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[9] = temp1;
    temp2 = _mm_aeskeygenassist_si128(temp1, 0x36);
    aes128_key_assist(&temp1, &temp2);
    enc_round_keys[10] = temp1;
}
References aes128_key_assist(), and AES_128_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes192_invert_round_keys()
void aes192_invert_round_keys (const __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_192_NUM_ROUND_KEYS])
Inverts the AES-192 encryption round keys into decryption round keys.
Parameters
enc_round_keys Input array of 13 encryption round keys from aes192_key_expansion().
dec_round_keys Output array of 13 decryption round keys.
Definition at line 259 of file aes_key_expansion.c.
{
    // First decryption round key = last encryption round key
    dec_round_keys[0]  = enc_round_keys[12];
    // Apply aesimc to intermediate keys (in reverse order)
    dec_round_keys[1]  = _mm_aesimc_si128(enc_round_keys[11]);
    dec_round_keys[2]  = _mm_aesimc_si128(enc_round_keys[10]);
    dec_round_keys[3]  = _mm_aesimc_si128(enc_round_keys[9]);
    dec_round_keys[4]  = _mm_aesimc_si128(enc_round_keys[8]);
    dec_round_keys[5]  = _mm_aesimc_si128(enc_round_keys[7]);
    dec_round_keys[6]  = _mm_aesimc_si128(enc_round_keys[6]);
    dec_round_keys[7]  = _mm_aesimc_si128(enc_round_keys[5]);
    dec_round_keys[8]  = _mm_aesimc_si128(enc_round_keys[4]);
    dec_round_keys[9]  = _mm_aesimc_si128(enc_round_keys[3]);
    dec_round_keys[10] = _mm_aesimc_si128(enc_round_keys[2]);
    dec_round_keys[11] = _mm_aesimc_si128(enc_round_keys[1]);
    // Last decryption round key = first encryption round key
    dec_round_keys[12] = enc_round_keys[0];
}
References AES_192_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes192_key_expansion()
void aes192_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_192_NUM_ROUND_KEYS])
Expands a 192-bit AES user key into the encryption round key schedule.
Parameters
user_key The 192-bit user key (as two __m128i blocks, only 192 bits used).
enc_round_keys Output array of 13 __m128i encryption round keys (AES_192_WORDS).
Definition at line 109 of file aes_key_expansion.c.
{
    __m128i temp1 = user_key[0];
    __m128i temp3 = user_key[1];
    __m128i temp2;
    enc_round_keys[0] = temp1; // Store the original user key as round key 0
    enc_round_keys[1] = temp3; // Store the second part of the user key as round key 1
    // Generate remaining 11 round keys
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x1);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[1] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[1]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[2] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x2);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[3] = temp1;
    enc_round_keys[4] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x4);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[4] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[4]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[5] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x8);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[6] = temp1;
    enc_round_keys[7] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x10);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[7] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[7]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[8] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x20);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[9] = temp1;
    enc_round_keys[10] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x40);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[10] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(enc_round_keys[10]), _mm_castsi128_pd(temp1), 0));
    enc_round_keys[11] = _mm_castpd_si128(_mm_shuffle_pd(_mm_castsi128_pd(temp1), _mm_castsi128_pd(temp3), 1));
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x80);
    aes192_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[12] = temp1;
}
References aes192_key_assist(), and AES_192_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes256_invert_round_keys()
void aes256_invert_round_keys (const __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS], __m128i dec_round_keys[AES_256_NUM_ROUND_KEYS])
Inverts the AES-256 encryption round keys into decryption round keys.
Parameters
enc_round_keys Input array of 15 encryption round keys from aes256_key_expansion().
dec_round_keys Output array of 15 decryption round keys.
Definition at line 281 of file aes_key_expansion.c.
{
    // First decryption round key = last encryption round key
    dec_round_keys[0]  = enc_round_keys[14];
    // Apply aesimc to intermediate keys (in reverse order)
    dec_round_keys[1]  = _mm_aesimc_si128(enc_round_keys[13]);
    dec_round_keys[2]  = _mm_aesimc_si128(enc_round_keys[12]);
    dec_round_keys[3]  = _mm_aesimc_si128(enc_round_keys[11]);
    dec_round_keys[4]  = _mm_aesimc_si128(enc_round_keys[10]);
    dec_round_keys[5]  = _mm_aesimc_si128(enc_round_keys[9]);
    dec_round_keys[6]  = _mm_aesimc_si128(enc_round_keys[8]);
    dec_round_keys[7]  = _mm_aesimc_si128(enc_round_keys[7]);
    dec_round_keys[8]  = _mm_aesimc_si128(enc_round_keys[6]);
    dec_round_keys[9]  = _mm_aesimc_si128(enc_round_keys[5]);
    dec_round_keys[10] = _mm_aesimc_si128(enc_round_keys[4]);
    dec_round_keys[11] = _mm_aesimc_si128(enc_round_keys[3]);
    dec_round_keys[12] = _mm_aesimc_si128(enc_round_keys[2]);
    dec_round_keys[13] = _mm_aesimc_si128(enc_round_keys[1]);
    // Last decryption round key = first encryption round key
    dec_round_keys[14] = enc_round_keys[0];
}
References AES_256_NUM_ROUND_KEYS.
Referenced by aes_context_init().
aes256_key_expansion()
void aes256_key_expansion (const __m128i user_key[2], __m128i enc_round_keys[AES_256_NUM_ROUND_KEYS])
Expands a 256-bit AES user key into the encryption round key schedule.
Parameters
user_key The 256-bit user key (two full __m128i blocks).
enc_round_keys Output array of 15 __m128i encryption round keys (AES_256_WORDS).
Definition at line 194 of file aes_key_expansion.c.
{
    __m128i temp1 = user_key[0]; // First half of the user key
    __m128i temp3 = user_key[1]; // Second half of the user key
    __m128i temp2;
    enc_round_keys[0] = temp1;
    enc_round_keys[1] = temp3;
    // Generate remaining 13 round keys
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x01);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[2] = temp1;
    enc_round_keys[3] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x02);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[4] = temp1;
    enc_round_keys[5] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x04);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[6] = temp1;
    enc_round_keys[7] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x08);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[8] = temp1;
    enc_round_keys[9] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x10);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[10] = temp1;
    enc_round_keys[11] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x20);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[12] = temp1;
    enc_round_keys[13] = temp3;
    temp2 = _mm_aeskeygenassist_si128(temp3, 0x40);
    aes256_key_assist(&temp1, &temp2, &temp3);
    enc_round_keys[14] = temp1;
}
References aes256_key_assist(), and AES_256_NUM_ROUND_KEYS.
Referenced by aes_context_init().