AES-NI: aes_padding.h File Reference
aes_padding.h File Reference
AES block cipher padding and unpadding utilities.
#include <stdint.h>
#include <stddef.h>
Enumerations
enum aes_padding_t { AES_PADDING_PKCS7 , AES_PADDING_ZERO , AES_PADDING_ANSIX923 }
Supported AES padding schemes.
Functions
uint8_t * aes_add_padding (const uint8_t *input, size_t input_len, size_t *padded_size, aes_padding_t padding)
Applies the selected padding scheme to input data.
size_t aes_remove_padding (uint8_t *input, size_t input_len, aes_padding_t padding)
Removes padding from a previously padded buffer.
Detailed Description
AES block cipher padding and unpadding utilities.
This header provides functions for applying and removing padding schemes commonly used with AES block ciphers. These functions help ensure that input data aligns to the AES block size (16 bytes) as required by most AES modes.
Supported padding schemes:
PKCS#7: Standard padding where each byte of the padding is equal to the number of padding bytes.
Zero padding: Pads with 0x00 bytes. Suitable only when data does not naturally end with 0x00.
ANSI X.923: Pads with 0x00 bytes followed by a final byte indicating the length of the padding.
Padding must be applied before encryption and removed after decryption.
Definition in file aes_padding.h.
Enumeration Type Documentation
aes_padding_t
enum aes_padding_t
Supported AES padding schemes.
Enumerator
AES_PADDING_PKCS7
PKCS#7 padding (standard for block ciphers)
AES_PADDING_ZERO
Zero padding (zeros added until block size)
AES_PADDING_ANSIX923
ANSI X.923 padding (zeros + padding length byte)
Definition at line 28 of file aes_padding.h.
             {
    AES_PADDING_PKCS7,
    AES_PADDING_ZERO,
    AES_PADDING_ANSIX923
} aes_padding_t;
Function Documentation
aes_add_padding()
uint8_t * aes_add_padding (const uint8_t * input, size_t input_len, size_t * padded_size, aes_padding_t padding)
Applies the selected padding scheme to input data.
This function allocates a new buffer containing the original input data followed by the appropriate padding to align it with the AES block size (16 bytes). The caller is responsible for freeing the returned buffer.
Parameters
input Pointer to the input data to be padded.
input_len Length of the input data in bytes.
padded_size Output pointer to receive the length of the padded data.
padding Padding scheme to apply (e.g., PKCS#7, ZERO, ANSI X.923).
Returns
Pointer to the newly allocated, padded buffer. NULL on error.
Definition at line 52 of file aes_padding.c.
{
    if (!input || !padded_size) return NULL;
    size_t pad_len = AES_BLOCK_SIZE - (input_len % AES_BLOCK_SIZE);
    if (pad_len == AES_BLOCK_SIZE) pad_len = AES_BLOCK_SIZE;
    *padded_size = input_len + pad_len;
    uint8_t* padded_input = malloc(*padded_size);
    if (!padded_input) return NULL;
    memcpy(padded_input, input, input_len);
    switch (padding)
    {
        case AES_PADDING_PKCS7: aes_pcks7_pad(padded_input, input_len, pad_len); break;
        case AES_PADDING_ZERO: aes_zero_pad(padded_input, input_len, pad_len); break;
        case AES_PADDING_ANSIX923: aes_ansix923_pad(padded_input, input_len, pad_len); break;
        default:
            free(padded_input);
            return NULL;
    }
    return padded_input;
}
References aes_ansix923_pad(), AES_BLOCK_SIZE, AES_PADDING_ANSIX923, AES_PADDING_PKCS7, AES_PADDING_ZERO, aes_pcks7_pad(), and aes_zero_pad().
Referenced by encrypt_mode().
aes_remove_padding()
size_t aes_remove_padding (uint8_t * input, size_t input_len, aes_padding_t padding)
Removes padding from a previously padded buffer.
This function inspects the final block of data and validates the padding according to the selected scheme. It returns the original length of the unpadded data.
Parameters
input Pointer to the padded buffer.
input_len Total length of the buffer in bytes (must be a multiple of AES block size).
padding Padding scheme used during encryption.
Returns
The length of the data after removing padding, or 0 if padding is invalid.
Definition at line 144 of file aes_padding.c.
{
    if (input_len == 0 || input_len % AES_BLOCK_SIZE != 0)
        return 0;
    uint8_t pad_len = input[input_len - 1];
    switch (padding)
    {
        case AES_PADDING_PKCS7: return aes_pcks7_unpad(input, input_len, pad_len);
        case AES_PADDING_ZERO: return aes_zero_unpad(input, input_len);
        case AES_PADDING_ANSIX923: return aes_ansix923_unpad(input, input_len, pad_len);
        default: return 0;
    }
}
References aes_ansix923_unpad(), AES_BLOCK_SIZE, AES_PADDING_ANSIX923, AES_PADDING_PKCS7, AES_PADDING_ZERO, aes_pcks7_unpad(), and aes_zero_unpad().
Referenced by decrypt_mode().