AES-NI: aes_context.h File Reference
aes_context.h File Reference
AES context definition and initialization for AES-128, AES-192, and AES-256.
#include "aes/core/aes_constants.h"
#include <stdint.h>
#include <emmintrin.h>
#include <wmmintrin.h>
Data Structures
struct aes_context_t
AES context structure containing round keys for encryption and decryption.
Typedefs
typedef void(* aes_encrypt_func_t) (const __m128i plaintext, __m128i *ciphertext, const __m128i *enc_round_keys)
Function pointer type for AES encryption and decryption functions.
Enumerations
enum aes_key_size_t { AES_128 = AES_128_KEY_SIZE , AES_192 = AES_192_KEY_SIZE , AES_256 = AES_256_KEY_SIZE }
Enumeration of supported AES key sizes (in bytes).
Functions
int aes_context_init (aes_context_t *ctx, const uint8_t *key, size_t key_size)
Initializes an AES context by expanding the encryption and decryption keys.
Detailed Description
AES context definition and initialization for AES-128, AES-192, and AES-256.
This header defines the aes_context_t structure, which holds encryption and decryption round keys, as well as function pointers for block-level AES operations.
The context is initialized using aes_context_init() and can then be reused for multiple encryption/decryption calls with the associated key.
Definition in file aes_context.h.
Typedef Documentation
aes_encrypt_func_t
typedef void(* aes_encrypt_func_t) (const __m128i plaintext, __m128i *ciphertext, const __m128i *enc_round_keys)
Function pointer type for AES encryption and decryption functions.
This allows for dynamic selection of the encryption/decryption function based on key size.
Parameters
plaintext Input 16-byte block to encrypt/decrypt.
ciphertext Output pointer to receive the encrypted/decrypted 16-byte block.
enc_round_keys Array of round keys for encryption/decryption.
Definition at line 42 of file aes_context.h.
Enumeration Type Documentation
aes_key_size_t
enum aes_key_size_t
Enumeration of supported AES key sizes (in bytes).
Enumerator
AES_128
AES-128 uses 16-byte keys.
AES_192
AES-192 uses 24-byte keys.
AES_256
AES-256 uses 32-byte keys.
Definition at line 27 of file aes_context.h.
             {
    AES_128 = AES_128_KEY_SIZE,
    AES_192 = AES_192_KEY_SIZE,
    AES_256 = AES_256_KEY_SIZE
} aes_key_size_t;
Function Documentation
aes_context_init()
int aes_context_init (aes_context_t * ctx, const uint8_t * key, size_t key_size)
Initializes an AES context by expanding the encryption and decryption keys.
Parameters
ctx Pointer to the AES context to initialize.
key Raw AES key (must be 16, 24, or 32 bytes depending on AES version).
key_size Size of the key in bytes (must match AES_128, AES_192, or AES_256).
Returns
0 on success, non-zero on failure (e.g., invalid key size or null pointers).
Definition at line 7 of file aes_context.c.
{
    if (!ctx || !key)
        return 1;
    switch (key_size)
    {
        // AES_128
        case AES_128:
        {
            ctx->key_size = AES_128;
            aes128_key_expansion(_mm_loadu_si128((const __m128i*)key), ctx->enc_round_keys);
            aes128_invert_round_keys(ctx->enc_round_keys, ctx->dec_round_keys);
            ctx->encrypt_func = (aes_encrypt_func_t)aes128_encrypt_block;
            ctx->decrypt_func = (aes_encrypt_func_t)aes128_decrypt_block;
            break;
        }
        // AES_192
        case AES_192:
        {
            ctx->key_size = AES_192;
            __m128i key192[2] = {
                _mm_loadu_si128((const __m128i*)key),
                _mm_loadu_si128((const __m128i*)(key + 16))
            };
            aes192_key_expansion(key192, ctx->enc_round_keys);
            aes192_invert_round_keys(ctx->enc_round_keys, ctx->dec_round_keys);
            ctx->encrypt_func = (aes_encrypt_func_t)aes192_encrypt_block;
            ctx->decrypt_func = (aes_encrypt_func_t)aes192_decrypt_block;
            break;
        }
        // AES_256
        case AES_256:
        {
            ctx->key_size = AES_256;
            __m128i key256[2] = {
                _mm_loadu_si128((const __m128i*)key),
                _mm_loadu_si128((const __m128i*)(key + 16))
            };
            aes256_key_expansion(key256, ctx->enc_round_keys);
            aes256_invert_round_keys(ctx->enc_round_keys, ctx->dec_round_keys);
            ctx->encrypt_func = (aes_encrypt_func_t)aes256_encrypt_block;
            ctx->decrypt_func = (aes_encrypt_func_t)aes256_decrypt_block;
            break;
        }
        default:
            return 1;
    }
    return 0;
}
References aes128_decrypt_block(), aes128_encrypt_block(), aes128_invert_round_keys(), aes128_key_expansion(), aes192_decrypt_block(), aes192_encrypt_block(), aes192_invert_round_keys(), aes192_key_expansion(), aes256_decrypt_block(), aes256_encrypt_block(), aes256_invert_round_keys(), aes256_key_expansion(), AES_128, AES_192, AES_256, aes_context_t::dec_round_keys, aes_context_t::decrypt_func, aes_context_t::enc_round_keys, aes_context_t::encrypt_func, and aes_context_t::key_size.
Referenced by parse_args().