AES-NI: aes_padding.c File Reference
aes_padding.c File Reference
#include "aes/padding/aes_padding.h"
#include "aes/core/aes_constants.h"
#include <stdlib.h>
#include <string.h>
Functions
static void aes_pcks7_pad (uint8_t *input, size_t input_len, size_t pad_len)
Applies PKCS#7 padding to the input buffer.
static void aes_zero_pad (uint8_t *input, size_t input_len, size_t pad_len)
Applies zero padding to the input buffer.
static void aes_ansix923_pad (uint8_t *input, size_t input_len, size_t pad_len)
Applies ANSI X.923 padding to the input buffer.
uint8_t * aes_add_padding (const uint8_t *input, size_t input_len, size_t *padded_size, aes_padding_t padding)
Applies the selected padding scheme to input data.
static size_t aes_pcks7_unpad (uint8_t *input, size_t input_len, size_t pad_len)
Removes PKCS#7 padding from a padded buffer.
static size_t aes_zero_unpad (uint8_t *input, size_t input_len)
Removes zero padding from a padded buffer.
static size_t aes_ansix923_unpad (uint8_t *input, size_t input_len, size_t pad_len)
Removes ANSI X.923 padding from a padded buffer.
size_t aes_remove_padding (uint8_t *input, size_t input_len, aes_padding_t padding)
Removes padding from a previously padded buffer.
Function Documentation
aes_add_padding()
uint8_t * aes_add_padding (const uint8_t * input, size_t input_len, size_t * padded_size, aes_padding_t padding)
Applies the selected padding scheme to input data.
This function allocates a new buffer containing the original input data followed by the appropriate padding to align it with the AES block size (16 bytes). The caller is responsible for freeing the returned buffer.
Parameters
input Pointer to the input data to be padded.
input_len Length of the input data in bytes.
padded_size Output pointer to receive the length of the padded data.
padding Padding scheme to apply (e.g., PKCS#7, ZERO, ANSI X.923).
Returns
Pointer to the newly allocated, padded buffer. NULL on error.
Definition at line 52 of file aes_padding.c.
{
    if (!input || !padded_size) return NULL;
    size_t pad_len = AES_BLOCK_SIZE - (input_len % AES_BLOCK_SIZE);
    if (pad_len == AES_BLOCK_SIZE) pad_len = AES_BLOCK_SIZE;
    *padded_size = input_len + pad_len;
    uint8_t* padded_input = malloc(*padded_size);
    if (!padded_input) return NULL;
    memcpy(padded_input, input, input_len);
    switch (padding)
    {
        case AES_PADDING_PKCS7: aes_pcks7_pad(padded_input, input_len, pad_len); break;
        case AES_PADDING_ZERO: aes_zero_pad(padded_input, input_len, pad_len); break;
        case AES_PADDING_ANSIX923: aes_ansix923_pad(padded_input, input_len, pad_len); break;
        default:
            free(padded_input);
            return NULL;
    }
    return padded_input;
}
References aes_ansix923_pad(), AES_BLOCK_SIZE, AES_PADDING_ANSIX923, AES_PADDING_PKCS7, AES_PADDING_ZERO, aes_pcks7_pad(), and aes_zero_pad().
Referenced by encrypt_mode().
aes_ansix923_pad()
static void aes_ansix923_pad (uint8_t * input, size_t input_len, size_t pad_len) inline static
Applies ANSI X.923 padding to the input buffer.
Fills the padding space with 0x00 bytes, except for the last byte, which contains the number of padding bytes added.
Parameters
input Pointer to the buffer (must have enough space for padding).
input_len Length of the original data in bytes.
pad_len Number of bytes to pad (1 to AES_BLOCK_SIZE).
Definition at line 46 of file aes_padding.c.
{
    memset(input + input_len, 0x00, pad_len - 1);
    input[input_len + pad_len - 1] = (uint8_t)pad_len;
}
Referenced by aes_add_padding().
aes_ansix923_unpad()
static size_t aes_ansix923_unpad (uint8_t * input, size_t input_len, size_t pad_len) inline static
Removes ANSI X.923 padding from a padded buffer.
This function verifies that the padding bytes (except the last one) are all 0x00 and that the last byte contains the correct padding length. If the padding is invalid, it returns 0.
Parameters
input Pointer to the padded input buffer.
input_len Total length of the input buffer (must be a multiple of block size).
pad_len Padding length (value of the last byte).
Returns
Length of the data after removing padding, or 0 if padding is invalid.
Definition at line 133 of file aes_padding.c.
{
    for (size_t i = 1; i < pad_len; ++i)
    {
        if (input[input_len - 1 - i] != 0x00)
            return 0;
    }
    return input_len - pad_len;
}
Referenced by aes_remove_padding().
aes_pcks7_pad()
static void aes_pcks7_pad (uint8_t * input, size_t input_len, size_t pad_len) inline static
Applies PKCS#7 padding to the input buffer.
Pads the data so that the total length is a multiple of the AES block size. Each padding byte is set to the total number of padding bytes added.
Parameters
input Pointer to the buffer (must have enough space for padding).
input_len Length of the original data in bytes.
pad_len Number of bytes to pad (1 to AES_BLOCK_SIZE).
Definition at line 16 of file aes_padding.c.
{
    memset(input + input_len, (uint8_t)pad_len, pad_len);
}
Referenced by aes_add_padding().
aes_pcks7_unpad()
static size_t aes_pcks7_unpad (uint8_t * input, size_t input_len, size_t pad_len) inline static
Removes PKCS#7 padding from a padded buffer.
This function checks that all padding bytes at the end of the buffer are equal to the padding length value. If the padding is invalid, it returns 0.
Parameters
input Pointer to the padded input buffer.
input_len Total length of the input buffer (must be a multiple of block size).
pad_len Padding length (should be equal to the value of the last byte).
Returns
Length of the data after removing padding, or 0 if padding is invalid.
Definition at line 91 of file aes_padding.c.
{
    for (size_t i = 0; i < pad_len; ++i)
    {
        if (input[input_len - 1 - i] != pad_len)
            return 0;
    }
    return input_len - pad_len;
}
Referenced by aes_remove_padding().
aes_remove_padding()
size_t aes_remove_padding (uint8_t * input, size_t input_len, aes_padding_t padding)
Removes padding from a previously padded buffer.
This function inspects the final block of data and validates the padding according to the selected scheme. It returns the original length of the unpadded data.
Parameters
input Pointer to the padded buffer.
input_len Total length of the buffer in bytes (must be a multiple of AES block size).
padding Padding scheme used during encryption.
Returns
The length of the data after removing padding, or 0 if padding is invalid.
Definition at line 144 of file aes_padding.c.
{
    if (input_len == 0 || input_len % AES_BLOCK_SIZE != 0)
        return 0;
    uint8_t pad_len = input[input_len - 1];
    switch (padding)
    {
        case AES_PADDING_PKCS7: return aes_pcks7_unpad(input, input_len, pad_len);
        case AES_PADDING_ZERO: return aes_zero_unpad(input, input_len);
        case AES_PADDING_ANSIX923: return aes_ansix923_unpad(input, input_len, pad_len);
        default: return 0;
    }
}
References aes_ansix923_unpad(), AES_BLOCK_SIZE, AES_PADDING_ANSIX923, AES_PADDING_PKCS7, AES_PADDING_ZERO, aes_pcks7_unpad(), and aes_zero_unpad().
Referenced by decrypt_mode().
aes_zero_pad()
static void aes_zero_pad (uint8_t * input, size_t input_len, size_t pad_len) inline static
Applies zero padding to the input buffer.
Fills the padding space with 0x00 bytes. Only safe if the original data does not naturally end with zero bytes.
Parameters
input Pointer to the buffer (must have enough space for padding).
input_len Length of the original data in bytes.
pad_len Number of bytes to pad (1 to AES_BLOCK_SIZE).
Definition at line 31 of file aes_padding.c.
{
    memset(input + input_len, 0x00, pad_len);
}
Referenced by aes_add_padding().
aes_zero_unpad()
static size_t aes_zero_unpad (uint8_t * input, size_t input_len) inline static
Removes zero padding from a padded buffer.
This function removes trailing 0x00 bytes from the end of the buffer. It does not perform validation and assumes that the data does not naturally end with 0x00.
Parameters
input Pointer to the padded input buffer.
input_len Total length of the input buffer.
Returns
Length of the data after removing zero padding.
Definition at line 113 of file aes_padding.c.
{
    while (input_len > 0 && input[input_len - 1] == 0x00)
        input_len--;
    return input_len;
}
Referenced by aes_remove_padding().