AES-NI: utils.c File Reference
utils.c File Reference
#include "utils/utils.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void init_b64_reverse_table (void)
void show_message (int fatal, const char *format,...)
Displays an error or information message.
char * read_file (const char *filename, size_t *out_len)
Reads the entire contents of a text file into a null-terminated string.
int write_file (const char *filename, const char *text)
Writes a null-terminated string to a file.
char * base64_encode (const uint8_t *data, size_t input_len)
Encodes binary data into a Base64 null-terminated string.
uint8_t * base64_decode (const char *b64_string, size_t *output_len)
Decodes a Base64 string into raw binary data.
uint8_t * string_to_bytes (const char *str, size_t *out_len)
Converts a null-terminated string to a uint8_t byte array.
uint8_t * hex_string_to_bytes (const char *hex_str, size_t *out_len)
Converts a hexadecimal string to a uint8_t byte array.
char * bytes_to_string (const uint8_t *bytes, size_t len)
Converts a byte array to a null-terminated C string.
Variables
static const char b64_table [] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static uint8_t b64_reverse_table [256]
Function Documentation
base64_decode()
uint8_t * base64_decode (const char * b64_string, size_t * output_len)
Decodes a Base64 string into raw binary data.
This function decodes a Base64-encoded string back into its original binary representation. The output buffer is dynamically allocated and must be freed by the caller.
If the input string contains invalid Base64 characters or has an incorrect format, the function returns NULL.
Parameters
b64_string Null-terminated Base64-encoded string.
output_len Pointer to a size_t that will receive the output length (can be NULL).
Returns
Pointer to decoded binary data, or NULL on failure.
Definition at line 150 of file utils.c.
{
    if (!b64_string)
    {
        show_message(0, "Invalid Base64 string for decoding.");
        return NULL;
    }
    static int initialized = 0;
    if (!initialized)
    {
        init_b64_reverse_table();
        initialized = 1;
    }
    size_t input_len = strlen(b64_string);
    if (input_len % 4 != 0)
    {
        show_message(0, "Invalid Base64 string length: %zu", input_len);
        return NULL;
    }
    size_t out_len_est = input_len / 4 * 3;
    if (b64_string[input_len - 1] == '=') out_len_est--;
    if (b64_string[input_len - 2] == '=') out_len_est--;
    uint8_t* decoded = malloc(out_len_est);
    if (!decoded)
    {
        show_message(0, "Failed to allocate memory for Base64 decoding.");
        return NULL;
    }
    size_t j = 0;
    for (size_t i = 0; i < input_len; i += 4)
    {
        uint32_t sextet_a = b64_reverse_table[(unsigned char)b64_string[i]];
        uint32_t sextet_b = b64_reverse_table[(unsigned char)b64_string[i + 1]];
        uint32_t sextet_c = b64_reverse_table[(unsigned char)b64_string[i + 2]];
        uint32_t sextet_d = b64_reverse_table[(unsigned char)b64_string[i + 3]];
        if (sextet_a & 0x80 || sextet_b & 0x80 || sextet_c & 0x80 || sextet_d & 0x80)
        {
            free(decoded);
            show_message(0, "Invalid Base64 characters in input string.");
            return NULL;
        }
        uint32_t triple = (sextet_a << 18) | (sextet_b << 12) | (sextet_c << 6) | sextet_d;
        if (j < out_len_est) decoded[j++] = (triple >> 16) & 0xFF;
        if (j < out_len_est) decoded[j++] = (triple >> 8) & 0xFF;
        if (j < out_len_est) decoded[j++] = triple & 0xFF;
    }
    if (output_len)
        *output_len = out_len_est;
    return decoded;
}
References b64_reverse_table, init_b64_reverse_table(), and show_message().
Referenced by decrypt_mode().
base64_encode()
char * base64_encode (const uint8_t * data, size_t input_len)
Encodes binary data into a Base64 null-terminated string.
This function converts raw binary data into a Base64-encoded string using the standard Base64 alphabet (A-Z, a-z, 0-9, +, /).
The returned string is dynamically allocated and must be freed by the caller.
Parameters
data Pointer to the input binary data.
input_len Length of the input data in bytes.
Returns
Null-terminated Base64 string, or NULL on failure.
Definition at line 113 of file utils.c.
{
    if (!data || input_len == 0)
    {
        show_message(0, "Invalid input data for Base64 encoding.");
        return NULL;
    }
    size_t output_len = 4 * ((input_len + 2) / 3);
    char* encoded = malloc(output_len + 1);
    if (!encoded)
    {
        show_message(0, "Failed to allocate memory for Base64 encoding.");
        return NULL;
    }
    size_t j = 0;
    for (size_t i = 0; i < input_len; i += 3)
    {
        uint32_t octet_a = i < input_len ? data[i] : 0;
        uint32_t octet_b = (i + 1) < input_len ? data[i + 1] : 0;
        uint32_t octet_c = (i + 2) < input_len ? data[i + 2] : 0;
        uint32_t triple = (octet_a << 16) | (octet_b << 8) | octet_c;
        encoded[j++] = b64_table[(triple >> 18) & 0x3F];
        encoded[j++] = b64_table[(triple >> 12) & 0x3F];
        encoded[j++] = (i + 1 < input_len) ? b64_table[(triple >> 6) & 0x3F] : '=';
        encoded[j++] = (i + 2 < input_len) ? b64_table[triple & 0x3F] : '=';
    }
    encoded[output_len] = '\0';
    return encoded;
}
References b64_table, and show_message().
Referenced by encrypt_mode().
bytes_to_string()
char * bytes_to_string (const uint8_t * bytes, size_t len)
Converts a byte array to a null-terminated C string.
The returned string is dynamically allocated and must be freed by the caller. The input is assumed to be UTF-8 or ASCII-compatible (no validation is performed).
Parameters
bytes Pointer to the byte array.
len Length of the byte array.
Returns
Null-terminated string, or NULL on failure.
Definition at line 278 of file utils.c.
{
    if (!bytes || len == 0)
    {
        show_message(0, "Invalid byte array for conversion to string.");
        return NULL;
    }
    size_t new_len = 0;
    for (size_t i = 0; i < len; ++i)
    {
        if (bytes[i] == '\r' && (i + 1 < len) && bytes[i + 1] == '\n')
            ++i;
        new_len++;
    }
    char* str = malloc(new_len + 1);
    if (!str)
    {
        show_message(0, "Failed to allocate memory for byte array to string conversion.");
        return NULL;
    }
    size_t j = 0;
    for (size_t i = 0; i < len; ++i)
    {
        if (bytes[i] == '\r' && (i + 1 < len) && bytes[i + 1] == '\n')
        {
            str[j++] = '\n';
            ++i;
        }
        else
            str[j++] = bytes[i];
    }
    str[j] = '\0';
    return str;
}
References show_message().
Referenced by decrypt_mode().
hex_string_to_bytes()
uint8_t * hex_string_to_bytes (const char * hex_str, size_t * out_len)
Converts a hexadecimal string to a uint8_t byte array.
The input string must contain an even number of hex digits (0-9, a-f, A-F). The function allocates memory for the byte array, which must be freed by the caller.
Parameters
hex_str Null-terminated string containing hexadecimal characters.
out_len Pointer to size_t where the output length will be stored.
Returns
Pointer to byte array, or NULL on error (invalid input or memory allocation failure).
Definition at line 235 of file utils.c.
{
    if (!hex_str)
    {
        show_message(0, "Invalid hex string for conversion to bytes.");
        return NULL;
    }
    size_t hex_len = strlen(hex_str);
    if (hex_len % 2 != 0)
    {
        show_message(0, "Hex string must have an even length.");
        return NULL;
    }
    size_t byte_len = hex_len / 2;
    uint8_t* buffer = malloc(byte_len);
    if (!buffer)
    {
        show_message(0, "Failed to allocate memory for hex string to bytes conversion.");
        return NULL;
    }
    for (size_t i = 0; i < byte_len; ++i)
    {
        char byte_str[3] = { hex_str[2*i], hex_str[2*i + 1], '\0' };
        if (!isxdigit(byte_str[0]) || !isxdigit(byte_str[1]))
        {
            free(buffer);
            show_message(0, "Invalid hex character in string: %s", byte_str);
            return NULL;
        }
        buffer[i] = (uint8_t)strtoul(byte_str, NULL, 16);
    }
    if (out_len)
        *out_len = byte_len;
    return buffer;
}
References show_message().
Referenced by parse_args().
init_b64_reverse_table()
static void init_b64_reverse_table (void) static
Definition at line 11 of file utils.c.
{
    memset(b64_reverse_table, 0x80, 256);
    for (int i = 0; i < 64; i++)
        b64_reverse_table[(unsigned char)b64_table[i]] = (uint8_t)i;
    b64_reverse_table['='] = 0;
}
References b64_reverse_table, and b64_table.
Referenced by base64_decode().
read_file()
char * read_file (const char * filename, size_t * size)
Reads the entire contents of a text file into a null-terminated string.
Allocates and returns a buffer containing the contents of the file, including a null terminator. The length of the file (excluding the null byte) is returned through the size pointer.
The caller is responsible for freeing the returned buffer.
Parameters
filename Path to the input file.
size Pointer to a size_t that will hold the file length (can be NULL).
Returns
Pointer to the allocated string, or NULL if reading fails.
Definition at line 32 of file utils.c.
{
    FILE* file = fopen(filename, "rb");
    if (!file)
    {
        show_message(1, "Failed to open file: %s", filename);
        return NULL;
    }
    if (fseek(file, 0, SEEK_END) != 0)
    {
        fclose(file);
        show_message(0, "Failed to seek in file: %s", filename);
        return NULL;
    }
    long size = ftell(file);
    if (size < 0)
    {
        fclose(file);
        show_message(0, "Failed to get file size: %s", filename);
        return NULL;
    }
    rewind(file);
    char* buffer = malloc(size + 1);
    if (!buffer)
    {
        fclose(file);
        show_message(0, "Failed to allocate memory for file: %s", filename);
        return NULL;
    }
    if (fread(buffer, 1, size, file) != (size_t)size)
    {
        free(buffer);
        fclose(file);
        show_message(0, "Failed to read file: %s", filename);
        return NULL;
    }
    buffer[size] = '\0';
    if (fclose(file) != 0)
    {
        free(buffer);
        show_message(0, "Failed to close file after reading: %s", filename);
        return NULL;
    }
    if (out_len)
        *out_len = (size_t)size;
    return buffer;
}
References show_message().
Referenced by decrypt_mode(), and encrypt_mode().
show_message()
void show_message (int fatal, const char * format, ...)
Displays an error or information message.
Prints a formatted message to stderr. If the fatal flag is non-zero, the program will exit with EXIT_FAILURE after displaying the message.
Parameters
fatal Set to 1 to terminate the program after printing the message.
format printf-style format string.
... Additional arguments to format the message.
Definition at line 19 of file utils.c.
{
    va_list args;
    va_start(args, format);
    fprintf(stderr, "[MESSAGE] ");
    vfprintf(stderr, format, args);
    fprintf(stderr, "\n");
    va_end(args);
    if (fatal)
        exit(EXIT_FAILURE);
}
Referenced by base64_decode(), base64_encode(), bytes_to_string(), hex_string_to_bytes(), main(), parse_args(), read_file(), string_to_bytes(), and write_file().
string_to_bytes()
uint8_t * string_to_bytes (const char * str, size_t * out_len)
Converts a null-terminated string to a uint8_t byte array.
The returned buffer is dynamically allocated and must be freed by the caller. The length of the array (excluding the null terminator) is returned via out_len.
Parameters
str Null-terminated input string.
out_len Pointer to store the length of the resulting byte array.
Returns
Pointer to the uint8_t array, or NULL on failure.
Definition at line 211 of file utils.c.
{
    if (!str)
    {
        show_message(0, "Invalid string for conversion to bytes.");
        return NULL;
    }
    size_t len = strlen(str);
    uint8_t* buffer = malloc(len);
    if (!buffer)
    {
        show_message(0, "Failed to allocate memory for string to bytes conversion.");
        return NULL;
    }
    memcpy(buffer, str, len);
    if (out_len)
        *out_len = len;
    return buffer;
}
References show_message().
Referenced by encrypt_mode().
write_file()
int write_file (const char * filename, const char * data)
Writes a null-terminated string to a file.
Opens the file in text mode and writes the given string to it.
Parameters
filename Path to the output file.
data Null-terminated string to write.
Returns
0 on success, -1 on failure.
Definition at line 88 of file utils.c.
{
    FILE* file = fopen(filename, "w");
    if (!file)
    {
        show_message(0, "Failed to open file for writing: %s", filename);
        return -1;
    }
    if (fputs(text, file) == EOF)
    {
        fclose(file);
        show_message(0, "Failed to write to file: %s", filename);
        return -1;
    }
    if (fclose(file) != 0)
    {
        show_message(0, "Failed to close file after writing: %s", filename);
        return -1;
    }
    return 0;
}
References show_message().
Referenced by decrypt_mode(), and encrypt_mode().
Variable Documentation
b64_reverse_table
uint8_t b64_reverse_table[256] static
Definition at line 9 of file utils.c.
Referenced by base64_decode(), and init_b64_reverse_table().
b64_table
const char b64_table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" static
Definition at line 7 of file utils.c.
Referenced by base64_encode(), and init_b64_reverse_table().